Traceback (most recent call last):
  File "/Users/eduora/opt/anaconda3/envs/rl/lib/python3.9/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/eduora/opt/anaconda3/envs/rl/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/eduora/opt/anaconda3/envs/rl/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 530, in open
    return _file_openers[ext](found, mode=mode,
